// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Usar variables inyectadas por Vite via define
declare const __SUPABASE_URL__: string;
declare const __SUPABASE_KEY__: string;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || __SUPABASE_URL__;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || __SUPABASE_KEY__;

console.log('🔐 Supabase initialized:', {
  url: SUPABASE_URL?.substring(0, 40),
  key: SUPABASE_PUBLISHABLE_KEY?.substring(0, 25),
});

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});